# \ <section:var>
MODULE      = $(notdir $(CURDIR))
OS          = $(shell uname -s)
MACHINE     = $(shell uname -m)
# / <section:var>
# \ <section:dir>
CWD         = $(CURDIR)
DOC         = $(CWD)/doc
BIN         = $(CWD)/bin
SRC         = $(CWD)/src
TMP         = $(CWD)/tmp
# / <section:dir>
